"use client";

import type {
  Child,
  LessonPlan,
  ComplianceRecord,
  ParentCommunication,
} from "@/hooks/useSpacetimeDB";

export class WorkflowAutomationService {
  private static instance: WorkflowAutomationService;

  private constructor() {}

  public static getInstance(): WorkflowAutomationService {
    if (!WorkflowAutomationService.instance) {
      WorkflowAutomationService.instance = new WorkflowAutomationService();
    }
    return WorkflowAutomationService.instance;
  }

  async generateFrameworkAlignedLesson(
    framework: "HDLH" | "Flight" | "ELOF" | "Accueillir",
    ageGroup: string,
    topic: string,
    duration: number,
  ): Promise<Partial<LessonPlan>> {
    const frameworkGuidelines = this.getFrameworkGuidelines(framework);
    const ageGroupAdaptations = this.getAgeGroupAdaptations(ageGroup);

    const lessonPrompt = this.buildLessonPrompt(
      framework,
      ageGroup,
      topic,
      duration,
      frameworkGuidelines,
      ageGroupAdaptations,
    );

    try {
      const response = await fetch("/api/proxy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          protocol: "https",
          origin: "api.perplexity.ai",
          path: "/chat/completions",
          method: "POST",
          headers: {
            Authorization: "Bearer pplx-d41d8cd98f00b204e9800998ecf8427e",
            "Content-Type": "application/json",
          },
          body: {
            model: "llama-3.1-sonar-small-128k-online",
            messages: [{ role: "user", content: lessonPrompt }],
            max_tokens: 1500,
            temperature: 0.7,
          },
        }),
      });

      const data = (await response.json()) as any;
      const aiContent = data.choices?.[0]?.message?.content ?? "";

      return this.parseLessonContent(aiContent, framework, ageGroup, topic, duration);
    } catch (error) {
      console.error("AI lesson generation failed:", error);
      return this.generateFallbackLesson(framework, ageGroup, topic, duration);
    }
  }

  async trackDevelopmentMilestones(
    child: Child,
    newObservations: string[],
  ): Promise<Record<string, boolean>> {
    const currentMilestones = child.developmentMilestones;
    const updatedMilestones = { ...currentMilestones };

    const expectedMilestones = this.getExpectedMilestones(this.calculateAge(child.dateOfBirth));

    for (const observation of newObservations) {
      const detectedMilestones = await this.analyzeMilestoneAchievement(observation, expectedMilestones);
      detectedMilestones.forEach((milestone) => {
        updatedMilestones[milestone] = true;
      });
    }

    const newlyAchieved = this.getNewlyAchievedMilestones(currentMilestones, updatedMilestones);
    if (newlyAchieved.length > 0) {
      await this.triggerMilestoneReports(child, newlyAchieved);
    }

    return updatedMilestones;
  }

  async monitorComplianceStatus(): Promise<ComplianceRecord[]> {
    const upcomingDeadlines = this.calculateUpcomingDeadlines();
    const overdueItems = this.identifyOverdueCompliance();
    const autoGeneratedTasks: ComplianceRecord[] = [];

    for (const deadline of upcomingDeadlines) {
      if (this.shouldCreateAutomatedReminder(deadline)) {
        autoGeneratedTasks.push(this.createComplianceReminder(deadline));
      }
    }

    for (const overdueItem of overdueItems) {
      await this.escalateOverdueCompliance(overdueItem);
    }

    return autoGeneratedTasks;
  }

  async generateDailyReports(
    child: Child,
    activities: string[],
    meals: string[],
    naps: string[],
    additionalNotes = "",
  ): Promise<ParentCommunication> {
    const reportTemplate = this.buildDailyReportTemplate();

    const personalizedReport = await this.personalizeReport(child, reportTemplate, {
      activities,
      meals,
      naps,
      additionalNotes,
      milestones: this.getRecentMilestones(child),
      photos: [],
    });

    return {
      id: `daily-${child.id}-${new Date().toISOString().split("T")[0]}`,
      childId: child.id,
      parentId: child.parentIds[0] ?? "",
      type: "daily_report",
      title: `Daily Report for ${child.firstName}`,
      content: personalizedReport,
      timestamp: new Date().toISOString(),
      isRead: false,
    };
  }

  async autoScheduleActivities(
    children: Child[],
    availableStaff: string[],
    timeSlots: string[],
  ): Promise<{
    schedule: Record<string, any[]>;
    conflicts: string[];
    recommendations: string[];
  }> {
    const schedule: Record<string, any[]> = {};
    const conflicts: string[] = [];
    const recommendations: string[] = [];

    const ageGroups = this.groupChildrenByAge(children);
    const activityTypes = ["physical", "creative", "cognitive", "social", "quiet"];

    for (const timeSlot of timeSlots) {
      const slotActivities: any[] = [];

      for (const [ageRange, ageGroupChildren] of Object.entries(ageGroups)) {
        const optimalActivity = this.selectOptimalActivity(
          ageGroupChildren,
          timeSlot,
          activityTypes,
          availableStaff,
        );

        if (optimalActivity) {
          slotActivities.push({
            time: timeSlot,
            activity: optimalActivity,
            children: ageGroupChildren,
            staff: this.assignStaff(availableStaff, ageGroupChildren.length),
            ageGroup: ageRange,
          });
        } else {
          conflicts.push(`No suitable activity for ${ageRange} at ${timeSlot}`);
        }
      }

      schedule[timeSlot] = slotActivities;
    }

    recommendations.push(...this.generateScheduleRecommendations(schedule, conflicts));

    return { schedule, conflicts, recommendations };
  }

  private getFrameworkGuidelines(framework: "HDLH" | "Flight" | "ELOF" | "Accueillir"): string {
    const guidelines: Record<string, string> = {
      HDLH: `High/Scope methodology emphasizing:
        - Active learning through direct experience with people, objects, and ideas
        - Daily "plan-do-review" sequence
        - Learning environment with well-defined interest areas
        - Consistent daily routine with large and small group times`,

      Flight: `Flight curriculum focusing on:
        - Emergent curriculum based on children's interests
        - Project-based learning approach
        - Documentation of children's learning journey
        - Family and community involvement`,

      ELOF: `Early Learning Outcomes Framework emphasizing:
        - Comprehensive development across all domains
        - School readiness indicators
        - Culturally responsive practices
        - Family engagement strategies`,

      Accueillir: `Accueillir la petite enfance approach focusing on:
        - Respect for each child's individual rhythm
        - Creating secure emotional bonds
        - Supporting French language development
        - Cultural identity preservation`,
    };

    return guidelines[framework];
  }

  private getAgeGroupAdaptations(ageGroup: string): string {
    const adaptations: Record<string, string> = {
      infants: "Focus on sensory experiences, attachment, and basic care routines",
      toddlers: "Emphasis on exploration, language development, and self-help skills",
      preschool: "Complex play, pre-academic skills, and social-emotional development",
      "school-age": "Academic support, structured activities, and leadership opportunities",
    };

    return adaptations[ageGroup] ?? "Age-appropriate developmental activities";
  }

  private buildLessonPrompt(
    framework: string,
    ageGroup: string,
    topic: string,
    duration: number,
    guidelines: string,
    adaptations: string,
  ): string {
    return `Create a detailed lesson plan for Early Childhood Education with the following specifications:

Framework: ${framework}
Age Group: ${ageGroup}
Topic: ${topic}
Duration: ${duration} minutes

Framework Guidelines:
${guidelines}

Age Adaptations:
${adaptations}

Please provide a structured lesson plan including:
1. Clear learning objectives (2-3 specific, measurable goals)
2. Required materials list
3. Step-by-step activities breakdown
4. Assessment strategies
5. Adaptations for different learning styles
6. Safety considerations
7. Extension activities

Format the response as structured text that can be parsed into individual components.`;
  }

  private parseLessonContent(
    content: string,
    framework: "HDLH" | "Flight" | "ELOF" | "Accueillir",
    ageGroup: string,
    topic: string,
    duration: number,
  ): Partial<LessonPlan> {
    const sections = this.extractSections(content);

    return {
      title: `${topic} - ${framework} Approach`,
      description:
        sections.description || `${framework}-aligned lesson for ${ageGroup} focusing on ${topic}`,
      framework,
      ageGroup,
      duration,
      materials: this.extractList(sections.materials) ?? [`Materials for ${topic} activity`],
      objectives: this.extractList(sections.objectives) ?? [
        `Explore ${topic} concepts`,
        "Engage in hands-on learning",
      ],
      activities: this.extractList(sections.activities) ?? [`Interactive ${topic} exploration`],
      assessments: this.extractList(sections.assessments) ?? [
        "Observation",
        "Documentation",
        "Child reflection",
      ],
      isPublic: false,
    };
  }

  private generateFallbackLesson(
    framework: "HDLH" | "Flight" | "ELOF" | "Accueillir",
    ageGroup: string,
    topic: string,
    duration: number,
  ): Partial<LessonPlan> {
    return {
      title: `${topic} Exploration - ${framework}`,
      description: `Developmentally appropriate ${topic} activities following ${framework} methodology`,
      framework,
      ageGroup,
      duration,
      materials: ["Age-appropriate materials", "Safety equipment", "Documentation tools"],
      objectives: [
        `Explore ${topic} through hands-on experiences`,
        "Develop language and communication skills",
        "Foster creativity and problem-solving",
      ],
      activities: [
        "Opening circle discussion",
        `Interactive ${topic} exploration`,
        "Creative expression time",
        "Closing reflection",
      ],
      assessments: ["Observation notes", "Photo documentation", "Child portfolio entries"],
      isPublic: false,
    };
  }

  private extractSections(content: string): Record<string, string> {
    const sections: Record<string, string> = {};
    const sectionRegex = /(?:^|\n)(?:\d+\.\s*)?([A-Z][^:\n]+):\s*\n?((?:[^\n]+\n?)*?)(?=\n(?:\d+\.\s*)?[A-Z][^:\n]+:|$)/g;

    let match: RegExpExecArray | null;
    while ((match = sectionRegex.exec(content)) !== null) {
      const [, title, contentText] = match;
      sections[title.toLowerCase().replace(/\s+/g, "_")] = contentText.trim();
    }

    return sections;
  }

  private extractList(text: string | undefined): string[] | undefined {
    if (!text) {
      return undefined;
    }

    const listItems = text
      .split(/\n|;|,/)
      .map((item) => item.replace(/^[-*•]\s*/, "").trim())
      .filter((item) => item.length > 0);

    return listItems.length > 0 ? listItems : undefined;
  }

  private calculateAge(dateOfBirth: string): number {
    const birth = new Date(dateOfBirth);
    const today = new Date();
    const age =
      today.getFullYear() - birth.getFullYear() -
      (today.getMonth() < birth.getMonth() ||
      (today.getMonth() === birth.getMonth() && today.getDate() < birth.getDate())
        ? 1
        : 0);
    return Math.max(age, 0);
  }

  private getExpectedMilestones(ageInYears: number): string[] {
    const milestonesByAge: Record<number, string[]> = {
      0: ["smiles", "holds_head_up", "follows_objects", "responds_to_sounds"],
      1: ["walks", "first_words", "waves_bye", "picks_up_small_objects"],
      2: ["runs", "kicks_ball", "two_word_phrases", "plays_alongside_others"],
      3: ["pedals_tricycle", "speaks_clearly", "follows_instructions", "toilet_trained"],
      4: ["hops_on_one_foot", "tells_stories", "plays_cooperatively", "dresses_independently"],
      5: ["skips", "draws_person", "understands_rules", "ready_for_school"],
    };

    return milestonesByAge[ageInYears] ?? milestonesByAge[5];
  }

  private async analyzeMilestoneAchievement(
    observation: string,
    expectedMilestones: string[],
  ): Promise<string[]> {
    const detectedMilestones: string[] = [];

    expectedMilestones.forEach((milestone) => {
      const keywords = milestone.split("_");
      if (keywords.some((keyword) => observation.toLowerCase().includes(keyword))) {
        detectedMilestones.push(milestone);
      }
    });

    return detectedMilestones;
  }

  private getNewlyAchievedMilestones(
    previous: Record<string, boolean>,
    updated: Record<string, boolean>,
  ): string[] {
    return Object.keys(updated).filter((milestone) => updated[milestone] && !previous[milestone]);
  }

  private async triggerMilestoneReports(child: Child, milestones: string[]): Promise<void> {
    console.log(`Generating milestone reports for ${child.firstName}:`, milestones);
  }

  private calculateUpcomingDeadlines(): Array<{ type: string; date: string; description: string }> {
    const today = new Date();
    const deadlines: Array<{ type: string; date: string; description: string }> = [];

    deadlines.push({
      type: "safety_inspection",
      date: new Date(today.getFullYear() + 1, 2, 15).toISOString(),
      description: "Annual fire safety inspection due",
    });

    return deadlines;
  }

  private identifyOverdueCompliance(): ComplianceRecord[] {
    return [];
  }

  private shouldCreateAutomatedReminder(deadline: { date: string }): boolean {
    const deadlineDate = new Date(deadline.date);
    const today = new Date();
    const daysUntilDeadline = Math.ceil(
      (deadlineDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24),
    );

    return daysUntilDeadline <= 30;
  }

  private createComplianceReminder(deadline: {
    type: string;
    date: string;
    description: string;
  }): ComplianceRecord {
    return {
      id: `auto-${deadline.type}-${Date.now()}`,
      type: deadline.type as ComplianceRecord["type"],
      title: `Automated Reminder: ${deadline.description}`,
      description: "This is an automated reminder for upcoming compliance requirement.",
      status: "pending",
      dueDate: deadline.date,
      assignedTo: "administrator",
      documents: [],
      notes: "Auto-generated compliance reminder",
    };
  }

  private async escalateOverdueCompliance(item: ComplianceRecord): Promise<void> {
    console.log("Escalating overdue compliance:", item.title);
  }

  private buildDailyReportTemplate(): string {
    return `
**Daily Report for {childName}**

**Activities Today:**
{activities}

**Meals & Snacks:**
{meals}

**Rest & Nap Time:**
{naps}

**Development Highlights:**
{milestones}

**Photos & Moments:**
{photos}

**Additional Notes:**
{additionalNotes}

**Tomorrow's Plans:**
{tomorrowPlans}
    `.trim();
  }

  private async personalizeReport(
    child: Child,
    template: string,
    data: {
      activities: string[];
      meals: string[];
      naps: string[];
      additionalNotes: string;
      milestones: string[];
      photos: string[];
    },
  ): Promise<string> {
    let personalizedReport = template.replace("{childName}", child.firstName);

    personalizedReport = personalizedReport.replace(
      "{activities}",
      data.activities.map((activity) => `• ${activity}`).join("\n"),
    );

    personalizedReport = personalizedReport.replace(
      "{meals}",
      data.meals.map((meal) => `• ${meal}`).join("\n"),
    );

    personalizedReport = personalizedReport.replace(
      "{naps}",
      data.naps.map((nap) => `• ${nap}`).join("\n"),
    );

    personalizedReport = personalizedReport.replace(
      "{milestones}",
      data.milestones.length > 0
        ? data.milestones.map((milestone) => `• ${milestone}`).join("\n")
        : "No new milestones observed today",
    );

    personalizedReport = personalizedReport.replace(
      "{photos}",
      data.photos.length > 0 ? `${data.photos.length} photos captured` : "No photos today",
    );

    personalizedReport = personalizedReport.replace(
      "{additionalNotes}",
      data.additionalNotes || "No additional notes today",
    );

    personalizedReport = personalizedReport.replace(
      "{tomorrowPlans}",
      "Continuing with age-appropriate developmental activities",
    );

    return personalizedReport;
  }

  private getRecentMilestones(child: Child): string[] {
    return Object.entries(child.developmentMilestones)
      .filter(([, achieved]) => achieved)
      .map(([milestone]) => milestone.replace(/_/g, " "))
      .slice(-3);
  }

  private groupChildrenByAge(children: Child[]): Record<string, Child[]> {
    const groups: Record<string, Child[]> = {};

    children.forEach((child) => {
      const age = this.calculateAge(child.dateOfBirth);
      let ageGroup = "preschool";

      if (age < 1) ageGroup = "infants";
      else if (age < 3) ageGroup = "toddlers";
      else if (age < 5) ageGroup = "preschool";
      else ageGroup = "school-age";

      if (!groups[ageGroup]) groups[ageGroup] = [];
      groups[ageGroup].push(child);
    });

    return groups;
  }

  private selectOptimalActivity(
    children: Child[],
    timeSlot: string,
    activityTypes: string[],
    availableStaff: string[],
  ): any {
    const hour = parseInt(timeSlot.split(":")[0] ?? "", 10);

    if (!Number.isFinite(hour)) {
      return null;
    }

    if (hour < 9) return { type: "arrival", name: "Free play and breakfast" };
    if (hour < 11) return { type: "cognitive", name: "Learning centers" };
    if (hour < 12) return { type: "physical", name: "Outdoor play" };
    if (hour < 14) return { type: "quiet", name: "Lunch and quiet time" };
    if (hour < 16) return { type: "creative", name: "Art and music" };
    return { type: "social", name: "Group activities and departure" };
  }

  private assignStaff(availableStaff: string[], childrenCount: number): string[] {
    const requiredStaff = Math.max(1, Math.ceil(childrenCount / 4));
    return availableStaff.slice(0, requiredStaff);
  }

  private generateScheduleRecommendations(
    schedule: Record<string, any[]>,
    conflicts: string[],
  ): string[] {
    const recommendations: string[] = [];

    if (conflicts.length > 0) {
      recommendations.push(`Address ${conflicts.length} scheduling conflicts`);
    }

    recommendations.push("Consider adding transition time between activities");
    recommendations.push("Ensure outdoor time is scheduled during optimal weather");

    return recommendations;
  }
}

export const workflowAutomation = WorkflowAutomationService.getInstance();
